### ISSUE TITLE
Performance issues with water particles.

### ISSUE THREAD

**Issue by darkevilmac** [elytra/MovingWorld#16]

**Comment by Holgath** [comment]
I tried quickly with 21 pistons running at the same time with a simple timer. I didn’t get any lag. If you want I can try with a larger amount. Also I noticed that it only seems to affect the boats that are in the water. If I am using an airship I don’t get the same lag… unless I jump off the boat into the water below the airship. Then I get a lot of lag again even if I disassemble the ship. I noticed that if I turn off water particles using Optifine settings most of the lag goes away.


I decided to do a little bit more testing. The following paragraph is in the order I tested.


It doesn’t lag when I jump in the water with no mods using only the forge client. I get no lag using normal Minecraft boats with no mods. If I add the moving world and the Archimedes ships plus mods and jump in the water or use a normal Minecraft boat I don’t get lag. I don’t seem to get lag if I only build an airship. I only start to get the lag if I build a normal boat or put the airship in the water. Once I do that and the lag starts it happens every time I get in the water but is worse the closer to the boat I get. If I turn particles to minimal in the normal Minecraft settings the lag goes away again.

**Comment by Holgath** [comment]
Okay this is kind of weird.  I started a new map with the versions you told me to use.  I couldn’t get it to lag.  So I went to one of the old maps that had the lag already present and the lag was a problem again.  I went back to the new map and it I suddenly had lag on that map.  I repeated with another new map and I didn’t get lag until I went to a map that was already having lag problems.  I’m really not sure why it does this.  In all cases the lag stops when I turn off water particles.

**Comment by darkevilmac** [comment]
@Holgath I think I've found the cause of the issue, will be uploading a build for you to try on a test world to let me know if the issue is fixed.

**Comment by darkevilmac** [comment]
Here are the test builds, give em a try.

https://mega.nz/#!yMd2nLaS!lHKLEVKAfVK_H6eoBv-hGwaEKm1aHQsjuFwZHDvuuhE
https://mega.nz/#!vVVxHbLQ!QXnuEcIOLPoxMJ4vMAAQ7HQcIWyoNK5uqwv66sAuq5c

**Comment by Holgath** [comment]
When I use the files that you gave me all I get is a crash.  Did you change something in both of them?  It seems to crash when I am using the version of Archimedes ships plus that you had me download.  I was able to get the moving worlds you sent me to load by loading the old version of Archimedes.  I didn't do any testing besides loading minecraft. Here is the crash report it spits out when loading both of the new ones.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-MC1.8-V1.8.1.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 10/25/15 8:58 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/PlayerSetSpawnEvent
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:492)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/PlayerSetSpawnEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetPublicMethods(Class.java:2894)
	at java.lang.Class.privateGetPublicMethods(Class.java:2909)
	at java.lang.Class.getMethods(Class.java:1607)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:60)
	at darkevilmac.archimedes.common.CommonProxy.registerEventHandlers(CommonProxy.java:28)
	at darkevilmac.archimedes.ArchimedesShipMod.initMod(ArchimedesShipMod.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.player.PlayerSetSpawnEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 129221928 bytes (123 MB) / 289411072 bytes (276 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1519 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1519.jar) 
	UCHI	Forge{11.14.3.1519} [Minecraft Forge] (forge-1.8-11.14.3.1519.jar) 
	UCHI	darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHI	MovingWorld{MC1.8-V1.8.1} [Moving World] (movingworld-MC1.8-V1.8.1.jar) 
	UCHE	ArchimedesShipsPlus{MC1.8-V1.8} [Archimedes' Ships Plus] (archimedesshipsplus-MC1.8-V1.8.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-MC1.8-V1.8.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.98' Renderer: 'GeForce GTX 650/PCIe/SSE2'

**Comment by Holgath** [comment]
I forgot to mention.  I wasn't using any other mods while testing.

**Comment by darkevilmac** [comment]
Update to at least MinecraftForge 1.8 1520

**Comment by Holgath** [comment]
Well I haven't had a whole lot of time to test.  When I did I still had the problem but not as bad.  I almost wonder if it has something to do with Forge itself and your ship doing the particles just made it show up worse.  I used Java Visual VM and took a snapshot of the CPU while it was happening.  I am trying to add it here so you can see it but I can't seem to do it.  If you want it let me know.  I will try to test some more over the next few days.
![1 8 ship test](https://cloud.githubusercontent.com/assets/15178079/10721326/a7d77834-7b67-11e5-89f5-36ffa5ba37f4.png)

**Comment by Holgath** [comment]
It is definitely still doing it with the new versions.  It still only seems to happen when I am using your mod.  I can't get it to duplicate with just Forge but I am trying to find a way.  Just in case it is a Forge problem and not with your mod.

**Comment by darkevilmac** [comment]
Does lowering particles still fix it even in the newer builds? If so then I need to alter a different particle.

**Comment by Holgath** [comment]
Yes setting the particles to the lowest level brings the FPS back to where it should be.  The worst of it seems to happen if my character falls into the water while it is happening.

**Comment by darkevilmac** [comment]
Been fiddling with it again, does the lag only stop if particles are on minimal, or does putting it on decreased fix it as well?

**Comment by Holgath** [comment]
Only when it is on minimal.  I haven't tested the new one with optifine but on the other one turning off only water particles fixes it.
